export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REDUCE_QUANTITY = " REDUCEQUANTITY";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const CART_EMPTY = "CART_EMPTY";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const CLEAR_ITEMS = "CLEAR_ITEMS";
